### ISSUE TITLE
Add some support for additional icons

### ISSUE THREAD

**Issue by frague59** [redouane/django-fontawesome#12]
Hi, 
I've installed django-fontawesome from pip on my dev platform, and I'ld like to use in my prod server.

I do need the `map` icon from fontawesome, which looks like not to be in the `icons.yml` file. 
I can **_manually_** update the file, but I loose those changes when updating the prod venv with pip.

I've 2 questions : 
* could you update the module to update pypi  with this ?
* is it possible to re-generate the file from actual fontawesome website and to put it somewhere to the project file tree ? maybe through a management command ?

Thanks for your great job !

**Comment by redouane** [comment]
hi, i udpated the mapping (icons.yml) file. please use pip install --upgrade to upgrade to 0.2.6
the management command is interesting, but since fontawesome does not do releases every week i think that would overkill, for now atleast.
