### ISSUE TITLE
as_html  not working

### ISSUE THREAD

**Issue by nikoladang** [redouane/django-fontawesome#14]
## Inside my template, I have this code block:

```
{% if profile.icon_bookmark %}
    <td class="text-center">{{ profile.icon_bookmark.as_html }}</td></td>
{% else %}
    hello
{% endif %}
```

---

Nothing show in my rendered html file. I don't know why.

**Comment by aleksandrmaksimoviclt** [comment]
Have you figured out the root of issue ?
@nikoladang

**Comment by icdsarch** [comment]
I've tried this, but isn't showing the icon, althout the hml inspector shows it, there isn't a render. Do you know why?

**Comment by redouane** [comment]
please use latest master / pypi
