### ISSUE TITLE
No space before style attribute

### ISSUE THREAD

**Issue by kovtunos** [redouane/django-fontawesome#19]
Hi! I put this code into my template:
`{% fontawesome_icon 'user' color='gray' %}`

Here's the output:
`<i title="" class="fa fa-user"style="color:gray;">`

As you can see there's no space between class and style attributes.
I'm using Django 1.9.6  for my project.

Anyway, thanks for the package, it really helpful.

**Comment by redouane** [comment]
fixed in latest master / pypi, thanks.
