### ISSUE TITLE
Can't see icons in admin panel

### ISSUE THREAD

**Issue by shaniqwa** [redouane/django-fontawesome#31]
Hi,
i'm new to Django and trying to use this nice lib, I can't see the icons in admin panel: 
<img width="651" alt="screen shot 2017-05-17 at 11 06 00" src="https://cloud.githubusercontent.com/assets/9408766/26144329/0f4eb4ba-3af1-11e7-8a7f-7b9b3ae2f67c.png">

Any ideas what is wrong ?
Thanks
Shani

**Comment by silverfix** [comment]
+1

**Comment by kladiv** [comment]
+1

**Comment by shaniqwa** [comment]
I used version 1.11.1 
after few other things didn't work for me I installed 1.9.9 instead, and icons now work.

**Comment by atiberghien** [comment]
Django 1.11 breaks icon display in dropdown as they remove the render_option method in Select widget.
[PR#32](https://github.com/redouane/django-fontawesome/pull/32) will fix it

**Comment by redouane** [comment]
PR#32 merged; thanks
